/** @format */

// /** @format */

const UIData = {
  openMenu: true,
  customerName: "derek",
  shopData: {
    name: "Tony's Pizza",
    id: "tonys-pizza",
    logo: "./src/assets/theTacoFarmer.png",
    logoAlt: "taco",
    primaryColor: "red",
    secondaryColor: "yellow",
  },
  menuItems: [
    {
      name: "Pepperoni Pizza",
      key: "pepperoni-pizza",
      description: "Pepperoni pizza",
      price: 500,
      altString: "Pepperoni pizza",
      img: "./src/assets/beer.png",
      title: "A slice of pepperoni pizza",
    },
  ],
  orderList: [
    {
      customer: "Derek Fhreebs",
      pslice: 1,
      cost: 500,
      type: 0,
    },
    {
      customer: "Michelle Matzen",
      pslice: 2,
      cost: 100,
      type: 0,
    },
  ],
};

postMessage({
  openMenu: true,
  customerName: "derek",
  shopData: {
    name: "Tony's Pizza",
    id: "tonys-pizza",
    logo: "./src/assets/theTacoFarmer.png",
    logoAlt: "taco",
    primaryColor: "red",
    secondaryColor: "yellow",
  },
  menuItems: [
    {
      name: "Pepperoni Pizza",
      key: "pepperoni_pizza",
      description: "Pepperoni pizza",
      price: 500,
      altString: "Pepperoni pizza",
      img: "./src/assets/beer.png",
      title: "A slice of pepperoni pizza",
    },
  ],
  orderList: [
    {
      customer: "Derek Fhreebs",
      items: { pepperoni_slice: 3 },
      cost: 500,
      type: 0,
    },
    {
      customer: "Michelle Matzen",
      items: { pepperoni_slice: 3 },
      cost: 100,
      type: 0,
    },
  ],
});

// export const mockOrderList = [
//   {
//     customer: "Derek Fhreebs",
//     spicy: 2,
//     carne: 3,
//     green: 0,
//     corona: 0,
//     cost: 1999,
//     type: 0,
//   },
//   {
//     customer: "Derek Fhreebs",
//     spicy: 2,
//     carne: 3,
//     green: 0,
//     corona: 0,
//     cost: 1999,
//     type: 0,
//   },
// ];

// postMessage({
//   openMenu: true,
//   customerName: "Derek",
//   job: "taco",
//   shopData: {
//     name: "Tony's Pizza",
//     id: "tonys-pizza",
//     logo: "./src/assets/theTacoFarmer.png",
//     logoAlt: "taco",
//     primaryColor: "red",
//     secondaryColor: "yellow",
//     menuItems: [
//       {
//         name: "Corona",
//         key: "corona",
//         description: "An ice cold beer with your tacos.",
//         price: 100,
//         altString: "corona",
//         img: "./src/assets/beer.png",
//         title: "A Cold Corona",
//       },
//       {
//         name: "Pepperoni Pizza",
//         key: "cheese-pizza",
//         description: "cheese pizza",
//         price: 100,
//         altString: "cheese pizza",
//         img: "./src/assets/beer.png",
//         title: "A slice of cheese pizza",
//       },
//       {
//         name: "Pepperoni Pizza",
//         key: "pepperoni-pizza",
//         description: "Pepperoni pizza",
//         price: 1900,
//         altString: "Pepperoni pizza",
//         img: "./src/assets/beer.png",
//         title: "A slice of pepperoni pizza",
//       },
//     ],
//   },
//   orderList: [
//     {
//       customer: "Derek Fhreebs",
//       spicy: 2,
//       carne: 3,
//       green: 0,
//       corona: 0,
//       cost: 1999,
//       type: 0,
//     },
//     {
//       customer: "Derek Fhreebs",
//       spicy: 2,
//       carne: 3,
//       green: 0,
//       corona: 0,
//       cost: 1999,
//       type: 0,
//     },
//     {
//       customer: "Derek Fhreebs",
//       spicy: 2,
//       carne: 3,
//       green: 0,
//       corona: 0,
//       cost: 1999,
//       type: 0,
//     },
//     {
//       customer: "Derek Fhreebs",
//       spicy: 2,
//       carne: 3,
//       green: 0,
//       corona: 0,
//       cost: 1999,
//       type: 0,
//     },
//     {
//       customer: "Derek Fhreebs",
//       spicy: 2,
//       carne: 3,
//       green: 0,
//       corona: 0,
//       cost: 1999,
//       type: 0,
//     },
//     {
//       customer: "Derek Fhreebs",
//       spicy: 2,
//       carne: 3,
//       green: 0,
//       corona: 0,
//       cost: 1999,
//       type: 0,
//     },
//     {
//       customer: "Derek Fhreebs",
//       spicy: 2,
//       carne: 3,
//       green: 0,
//       corona: 0,
//       cost: 1999,
//       type: 0,
//     },
//     {
//       customer: "Derek Fhreebs",
//       spicy: 2,
//       carne: 3,
//       green: 0,
//       corona: 0,
//       cost: 1999,
//       type: 0,
//     },
//     {
//       customer: "Derek Fhreebs",
//       spicy: 2,
//       carne: 3,
//       green: 0,
//       corona: 0,
//       cost: 1999,
//       type: 0,
//     },
//     {
//       customer: "Derek Fhreebs",
//       spicy: 2,
//       carne: 3,
//       green: 0,
//       corona: 0,
//       cost: 1999,
//       type: 0,
//     },
//     {
//       customer: "Derek Fhreebs",
//       spicy: 2,
//       carne: 3,
//       green: 0,
//       corona: 0,
//       cost: 1999,
//       type: 0,
//     },
//   ],
// });
